{% set name = "etils" %}
{% set version = "1.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/google/etils/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 47fab05eb152caaa13773c90e0b7a089f8eab8ead11ba5fc5a96717d9b246165

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.10
    - flit-core >=3.8,<4
  run:
    - python >=3.10


test:
  imports:
    - etils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/etils/
  summary: Collection of common python utils
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ngam
    - traversaro
